export const TOPIC_GROUPS = {
  home: [
    'magick',
    'initiation',
    'thelema',
    'revelation',
    'doctrine',
    'publication',
    'archive',
    'scholarship',
    'biography',
    'legacy',
    'reception',
    'self_report',
  ],
  works: [
    'publication',
    'manual',
    'reference_work',
    'magazine',
    'autobiography',
    'fiction',
    'instruction',
    'doctrine',
    'theory',
    'editing',
    'transmission',
    'archive',
  ],
  tree: [
    'qabalah',
    'tarot',
    'magick',
    'initiation',
    'ritual',
    'enochian',
    'holy_guardian_angel',
    'aa',
    'curriculum',
    'instruction',
    'will',
    'correspondence',
  ],
  grades: [
    'initiation',
    'curriculum',
    'organization',
    'discipline',
    'instruction',
    'golden_dawn',
    'aa',
    'oto',
    'ritual',
    'qabalah',
    'doctrine',
    'theory',
  ],
  biography: [
    'birth',
    'childhood',
    'family',
    'education',
    'rebellion',
    'mountaineering',
    'travel',
    'exile',
    'death',
    'illness',
    'war',
    'home',
  ],
  people: [
    'relationship',
    'disciples',
    'rivalry',
    'scarlet_woman',
    'scholarship',
    'occult_circle',
    'social_network',
    'testimony',
    'biography',
    'reception',
    'legacy',
    'self_fashioning',
  ],
  saints: [
    'legacy',
    'reception',
    'occult_culture',
    'religion',
    'scholarship',
    'biography',
    'transmission',
    'archive',
    'postwar_reception',
    'pop_culture',
    'art',
    'thelema',
  ],
  dictionary: [
    'qabalah',
    'correspondence',
    'reference_work',
    'manual',
    'instruction',
    'doctrine',
    'theory',
    'aphorism',
    'poetry',
    'publication',
    'self_report',
    'archive',
  ],
} as const;

export type TopicGroupKey = keyof typeof TOPIC_GROUPS;
