import json
from pathlib import Path

from db_utils import open_db
from prose_enrichment import enrich_locations, expand_event_summary


ROOT = Path(__file__).resolve().parents[1]
TOPIC_TAXONOMY_PATH = ROOT / "database" / "topic_taxonomy.json"

PERSON_LABELS = {
    "PRS_000": "Aleister Crowley",
    "PRS_001": "Rose Edith Kelly",
    "PRS_002": "Victor Neuburg",
    "PRS_003": "Leah Hirsig",
    "PRS_004": "Mary Desti",
    "PRS_005": "Allan Bennett",
    "PRS_006": "MacGregor Mathers",
    "PRS_007": "W. B. Yeats",
    "PRS_008": "Jane Wolfe",
    "PRS_009": "Jack Parsons",
    "PRS_010": "Kenneth Grant",
    "PRS_011": "Israel Regardie",
    "PRS_012": "James Eshelman",
    "PRS_013": "Richard Kaczynski",
    "PRS_014": "Tobias Churton",
    "PRS_015": "Marco Pasi",
    "PRS_016": "Martin Starr",
}

WORK_LABELS = {
    "WKS_001": "Liber AL vel Legis",
    "WKS_002": "Book 4 / Liber ABA",
    "WKS_003": "The Vision and the Voice",
    "WKS_004": "777 and Other Qabalistic Writings",
    "WKS_005": "The Book of Thoth",
    "WKS_006": "The Equinox, Vol. I, No. 1",
    "WKS_007": "The Book of Lies",
    "WKS_008": "Liber Aleph vel CXI",
    "WKS_009": "The Blue Equinox",
    "WKS_010": "Magick in Theory and Practice",
    "WKS_011": "The Confessions of Aleister Crowley",
    "WKS_012": "Diary of a Drug Fiend",
}

LOCATIONS = [
    ("LOC_001", "Royal Leamington Spa, England", 52.2852, -1.5205, "Birthplace and the opening scene of the family pressure that Crowley later turned into anti-religious self-making."),
    ("LOC_002", "Boleskine House, Loch Ness", 57.266, -4.471, "The Abramelin site that became one of the signature places in Crowley's magical geography."),
    ("LOC_003", "London, England", 51.5074, -0.1278, "The crowded center of Golden Dawn politics, publishing, and much of Crowley's public life."),
    ("LOC_004", "Cairo, Egypt", 30.0444, 31.2357, "The Cairo Working city where Liber AL and the Thelemic narrative of revelation take shape."),
    ("LOC_005", "Bou Saada, Algeria", 35.2083, 4.1759, "Desert base for the Enochian Aethyr work with Victor Neuburg and the abyssal visionary current."),
    ("LOC_006", "Paris, France", 48.8566, 2.3522, "A recurring writing city for exile, publishing, and the later French phase of Crowley's career."),
    ("LOC_007", "Cefalu, Sicily", 38.0379, 14.0229, "Home of the Abbey of Thelema, the most visible attempt to make his system into a lived community."),
    ("LOC_008", "New York City, USA", 40.7128, -74.006, "A key American city for lectures, exile, occult networking, and the postwar afterlife of his work."),
    ("LOC_009", "Hastings, England", 50.8543, 0.5729, "Crowley's final home, where the public legend and the private body meet at the end of the archive."),
    ("LOC_010", "Blythe Road, London", 51.5106, -0.2062, "Administrative ground zero for Golden Dawn conflict and one of the order's most contested addresses."),
    ("LOC_011", "Redhill, Surrey, England", 51.2395, -0.1707, "The family base after Leamington, where religious discipline and domestic surveillance sharpened."),
    ("LOC_012", "Cambridge, England", 52.2053, 0.1218, "Trinity College and the undergraduate setting where Crowley's literary and occult self-formation accelerates."),
    ("LOC_013", "Schonbuhl Glacier, Swiss Alps", 46.8625, 8.2369, "Alpine terrain that fed Crowley's self-image as climber, ordeal-taker, and a man of will."),
    ("LOC_014", "Karakoram / K2", 35.8808, 76.5133, "The expedition zone where Crowley tested stamina, fellowship, and the mythology of endurance."),
    ("LOC_015", "Darjeeling, India", 27.041, 88.2663, "A Himalayan staging point for travel, study, and the eastern routes in Crowley's biography."),
    ("LOC_016", "Tunis, Tunisia", 36.8065, 10.1815, "The North African exile stop after the Abbey years collapsed and the community unraveled."),
    ("LOC_017", "Berlin, Germany", 52.52, 13.405, "A Weimar-era hub for art, sex, and social experimentation in Crowley's wider orbit."),
    ("LOC_018", "Oxford, England", 51.752, -1.2577, "A site of student life, literary contact, and the social worlds surrounding Crowley's circle."),
    ("LOC_019", "Caxton Hall, London", 51.4975, -0.1375, "The public performance venue where Crowley tested ritual theater before an audience."),
    ("LOC_020", "Pasadena, California", 34.1478, -118.1445, "A later American occult afterlife site linked to Jack Parsons and the Agape Lodge."),
]

LOCATIONS = enrich_locations(LOCATIONS)


def ev(
    event_id,
    date_start,
    date_end,
    title,
    summary,
    location_id,
    lane,
    document_id=None,
    people=(),
    topics=(),
    works=(),
):
    return {
        "id": event_id,
        "date_start": date_start,
        "date_end": date_end,
        "title": title,
        "summary": summary,
        "location_id": location_id,
        "lane": lane,
        "document_id": document_id,
        "people": tuple(people),
        "topics": tuple(topics),
        "works": tuple(works),
    }


def build_description(summary, topics, people, works):
    parts = [expand_event_summary(summary, topics, people, works, PERSON_LABELS, WORK_LABELS)]
    if topics:
        parts.append("Topics: " + ", ".join(topics))
    if people:
        parts.append("People: " + ", ".join(PERSON_LABELS[p] for p in people if p in PERSON_LABELS))
    if works:
        parts.append("Works: " + ", ".join(WORK_LABELS[w] for w in works if w in WORK_LABELS))
    return " | ".join(parts)


EVENTS = [
    ev(
        "EVT_001",
        "1875-10-12",
        None,
        "Birth of Edward Alexander Crowley",
        "Crowley is born in Royal Leamington Spa into a strict Plymouth Brethren family that shaped the antagonistic religious frame of his early life.",
        "LOC_001",
        "E",
        None,
        ["PRS_000"],
        ["birth", "family", "childhood", "religion"],
        [],
    ),
    ev(
        "EVT_002",
        "1887",
        "1887",
        "Father's death and family fracture",
        "The death of Frederick Crowley and the resulting family reorganization deepen the religious and emotional pressure around the young Crowley.",
        "LOC_011",
        "E",
        None,
        ["PRS_000"],
        ["family", "death", "childhood", "religion"],
        [],
    ),
    ev(
        "EVT_003",
        "1887",
        "1894",
        "Brethren schooling and rebellion",
        "Crowley moves through childhood schooling and religious discipline while developing the appetite for contradiction, secrecy, and literary self-fashioning that biographers trace throughout his life.",
        "LOC_011",
        "E",
        None,
        ["PRS_000"],
        ["education", "rebellion", "religion", "literary_formation"],
        [],
    ),
    ev(
        "EVT_004",
        "1889",
        "1895",
        "Malvern College years",
        "At Malvern Crowley sharpens both his hostility toward evangelical discipline and his attachment to poetry, sport, and the public performance of identity.",
        "LOC_011",
        "E",
        None,
        ["PRS_000"],
        ["education", "poetry", "rebellion", "social_formation"],
        [],
    ),
    ev(
        "EVT_005",
        "1895",
        "1898",
        "Trinity College, Cambridge",
        "Crowley enters Trinity College and begins the undergraduate phase in which climbing, verse, chess, and a widening occult curiosity begin to coexist.",
        "LOC_012",
        "E",
        None,
        ["PRS_000"],
        ["education", "literary_formation", "mountaineering", "travel"],
        [],
    ),
    ev(
        "EVT_006",
        "1895",
        "1897",
        "Alpine climbing and early self-making",
        "Crowley's alpine climbs and sporting exploits become part of the persona that later biography uses to frame his courage, recklessness, and will to endure.",
        "LOC_013",
        "E",
        None,
        ["PRS_000"],
        ["mountaineering", "travel", "self_fashioning"],
        [],
    ),
    ev(
        "EVT_007",
        "1898",
        "1898",
        "First publications and the motto Perdurabo",
        "Crowley begins to emerge publicly as a poet and adopts the motto Perdurabo, which becomes one of the most durable self-descriptions in the archive.",
        "LOC_012",
        "B",
        None,
        ["PRS_000"],
        ["poetry", "publication", "self_fashioning", "literary_formation"],
        [],
    ),
    ev(
        "EVT_008",
        "1898-11-18",
        None,
        "Initiation into the Golden Dawn",
        "Crowley is initiated into the Hermetic Order of the Golden Dawn and enters the ceremonial-current that organizes so much of his later symbolic language.",
        "LOC_003",
        "E",
        None,
        ["PRS_000"],
        ["golden_dawn", "initiation", "ritual", "magick"],
        [],
    ),
    ev(
        "EVT_009",
        "1898",
        "1899",
        "Early Golden Dawn temple work",
        "Crowley begins learning the order's grades, rituals, and symbolic maps, building the technical vocabulary that later underpins the A.'.A.'. and the published magical works.",
        "LOC_003",
        "A",
        None,
        ["PRS_000"],
        ["golden_dawn", "initiation", "ritual", "magick"],
        [],
    ),
    ev(
        "EVT_010",
        "1899-08",
        "1900",
        "Boleskine House and the Abramelin working",
        "Crowley purchases Boleskine House on Loch Ness and begins the Abramelin-inspired magical program that became a touchstone for later biographies of his spiritual ambition.",
        "LOC_002",
        "A",
        None,
        ["PRS_000"],
        ["abramelin", "magick", "ritual", "holy_guardian_angel", "travel"],
        [],
    ),
    ev(
        "EVT_011",
        "1900",
        "1900",
        "The Golden Dawn schism",
        "Crowley, Mathers, Yeats, and other key figures are caught in the collapse of the Golden Dawn's governing structure, turning organizational conflict into one of the recurring dramas of Crowley's career.",
        "LOC_010",
        "E",
        None,
        ["PRS_000", "PRS_006", "PRS_007"],
        ["golden_dawn", "rivalry", "organization", "conflict"],
        [],
    ),
    ev(
        "EVT_012",
        "1901",
        "1902",
        "Asian travel and mountain planning",
        "Crowley broadens his travel into Asia and the Himalayas, testing the mix of spiritual aspiration, athletic intensity, and curiosity that biographers repeatedly use to explain his later rhetoric of ordeal.",
        "LOC_015",
        "E",
        None,
        ["PRS_000"],
        ["travel", "mountaineering", "exploration", "literary_formation"],
        [],
    ),
    ev(
        "EVT_013",
        "1902",
        "1902",
        "The K2 expedition",
        "Crowley joins the K2 expedition and uses the mountain as a proving ground for endurance, leadership, and the public myth of will that he will carry into his magical writing.",
        "LOC_014",
        "E",
        None,
        ["PRS_000"],
        ["mountaineering", "travel", "will", "self_fashioning"],
        [],
    ),
    ev(
        "EVT_014",
        "1903",
        "1903",
        "Return to Britain and literary consolidation",
        "Crowley comes back from travel with a more elaborate public image: poet, mountaineer, occult aspirant, and increasingly a figure who treats life itself as a written ritual.",
        "LOC_003",
        "E",
        None,
        ["PRS_000"],
        ["publication", "literary_formation", "self_fashioning", "travel"],
        [],
    ),
    ev(
        "EVT_015",
        "1903-08-12",
        None,
        "Marriage to Rose Kelly",
        "Crowley marries Rose Edith Kelly, beginning the relationship that will become inseparable from the Cairo Working and the family history of the early Thelemic period.",
        "LOC_003",
        "E",
        None,
        ["PRS_000", "PRS_001"],
        ["relationship", "marriage", "family", "sexuality"],
        [],
    ),
    ev(
        "EVT_016",
        "1904",
        "1904",
        "Family life and the birth of Lilith",
        "Crowley and Rose try to settle into domestic routine, but the birth of their daughter Lilith makes the Cairo period feel more fragile, more intimate, and more charged with expectation.",
        "LOC_004",
        "E",
        None,
        ["PRS_000", "PRS_001"],
        ["family", "relationship", "childbirth", "domestic_life"],
        [],
    ),
    ev(
        "EVT_017",
        "1904-04-08",
        "1904-04-10",
        "The Cairo Working and Liber AL",
        "Crowley records the reception of Liber AL vel Legis in Cairo, the event that gives the Thelemic current its founding text, its signature voices, and its claim to revelation.",
        "LOC_004",
        "A",
        "DOC_WKS_001",
        ["PRS_000", "PRS_001"],
        ["cairo_working", "magick", "revelation", "thelema", "holy_guardian_angel"],
        ["WKS_001"],
    ),
    ev(
        "EVT_018",
        "1904",
        "1909",
        "Stele of Revealing and the Thelemic revelation cycle",
        "The Stele of Revealing becomes the visual hinge between object, ritual, and story as Crowley re-reads the Cairo event and gradually hardens the new aeon narrative around it.",
        "LOC_004",
        "A",
        "DOC_WKS_001",
        ["PRS_000", "PRS_001"],
        ["cairo_working", "thelema", "publication", "revelation"],
        ["WKS_001"],
    ),
    ev(
        "EVT_019",
        "1905",
        "1906",
        "Asian and Himalayan travel after Cairo",
        "Crowley keeps moving through Asia and the Himalayas, folding pilgrimage, study, and mountaineering into a travel phase that shows Thelema being carried abroad before the system is fully formalized.",
        "LOC_015",
        "E",
        None,
        ["PRS_000", "PRS_001"],
        ["travel", "mountaineering", "exploration", "religion"],
        [],
    ),
    ev(
        "EVT_020",
        "1907",
        "1907",
        "The A.'.A.'. begins to take shape",
        "Crowley and Allan Bennett begin shaping the initiatory current that becomes the A.'.A.'., giving Crowley a training architecture he can later hand to students instead of only narrating to them.",
        "LOC_003",
        "A",
        None,
        ["PRS_000", "PRS_005"],
        ["aa", "initiation", "organization", "magick"],
        [],
    ),
    ev(
        "EVT_021",
        "1908",
        "1909",
        "The A.'.A.'. instructional program",
        "Crowley refines the lessons, grades, and practices of the A.'.A.'. while trying to convert personal revelation into something that can be taught, repeated, and checked.",
        "LOC_003",
        "A",
        None,
        ["PRS_000", "PRS_005"],
        ["aa", "initiation", "curriculum", "magick"],
        [],
    ),
    ev(
        "EVT_022",
        "1909",
        "1909",
        "Launch of The Equinox",
        "Crowley launches The Equinox as a print engine for instruction, ritual, polemic, and the documentary self-fashioning that defines his middle career.",
        "LOC_003",
        "A",
        "DOC_WKS_006",
        ["PRS_000"],
        ["publication", "magazine", "magick", "propaganda"],
        ["WKS_006"],
    ),
    ev(
        "EVT_023",
        "1909",
        "1909",
        "777 and the correspondence tables",
        "Crowley consolidates his tables of correspondences into 777 and Other Qabalistic Writings, a reference book designed to be consulted, copied, and re-used rather than read once through.",
        "LOC_003",
        "A",
        "DOC_WKS_004",
        ["PRS_000"],
        ["publication", "qabalah", "reference_work", "magick"],
        ["WKS_004"],
    ),
    ev(
        "EVT_024",
        "1909-11",
        "1909-12",
        "The Vision and the Voice",
        "Crowley and Victor Neuburg work the Enochian Aethyrs in Bou Saada, producing the visionary record that later readers keep returning to for the Abyss, the Angel, and the desert atmosphere of the work.",
        "LOC_005",
        "A",
        "DOC_WKS_003",
        ["PRS_000", "PRS_002"],
        ["visionary_work", "enochian", "magick", "travel"],
        ["WKS_003"],
    ),
    ev(
        "EVT_025",
        "1910-10-19",
        "1910-11-30",
        "The Rites of Eleusis",
        "Crowley stages the Rites of Eleusis in London, turning ritual into theater and testing how far public performance can carry religious intensity.",
        "LOC_019",
        "A",
        None,
        ["PRS_000"],
        ["performance", "ritual", "theater", "public_magic"],
        [],
    ),
    ev(
        "EVT_026",
        "1911",
        "1911",
        "Liber Aleph vel CXI",
        "Crowley writes Liber Aleph as a letter-book of instruction and reflection, mixing magical doctrine, ethics, and intimate pedagogical voice.",
        "LOC_003",
        "B",
        "DOC_WKS_008",
        ["PRS_000"],
        ["publication", "instruction", "magick", "correspondence"],
        ["WKS_008"],
    ),
    ev(
        "EVT_027",
        "1912",
        "1912",
        "O.T.O. initiation and charter politics",
        "Crowley moves into the Ordo Templi Orientis orbit through initiation and charter politics, beginning the institutional negotiations that will keep following him long after the personal drama changes.",
        "LOC_003",
        "E",
        None,
        ["PRS_000"],
        ["oto", "initiation", "organization", "institutional_history"],
        [],
    ),
    ev(
        "EVT_028",
        "1912",
        "1913",
        "The Book of Lies appears",
        "Crowley publishes The Book of Lies, a compressed and paradoxical text that makes his symbolic style more aphoristic and more demanding at the same time.",
        "LOC_003",
        "A",
        "DOC_WKS_007",
        ["PRS_000"],
        ["publication", "aphorism", "magick", "qabalah"],
        ["WKS_007"],
    ),
    ev(
        "EVT_029",
        "1914",
        "1914",
        "The Paris Working",
        "Crowley works a sexual-magical program in Paris with Mary Desti and his wider circle, making intimacy, ritual, and performance into a deliberate technology rather than a private accident.",
        "LOC_006",
        "A",
        None,
        ["PRS_000", "PRS_004"],
        ["sex_magick", "relationship", "ritual", "magick", "travel"],
        [],
    ),
    ev(
        "EVT_030",
        "1914",
        "1918",
        "Wartime New York exile",
        "Crowley spends the war years in New York, where he becomes a public irritant, propagandist, and inveterate correspondent while continuing to narrate himself into being.",
        "LOC_008",
        "E",
        None,
        ["PRS_000", "PRS_004"],
        ["exile", "war", "correspondence", "politics", "travel"],
        [],
    ),
    ev(
        "EVT_031",
        "1915",
        "1916",
        "Mary Desti and the New York occult circle",
        "Crowley's New York years include close work with Mary Desti and a small circle of artists, occultists, and opportunists who keep his social world active even in exile.",
        "LOC_008",
        "E",
        None,
        ["PRS_000", "PRS_004"],
        ["relationship", "occult_circle", "social_network", "travel"],
        [],
    ),
    ev(
        "EVT_032",
        "1918",
        "1919",
        "The Amalantrah Working",
        "Crowley and Leah Hirsig participate in the Amalantrah Working, a New York ritual complex that folds sexual magic, visionary scripting, and elaborate invisible correspondence into one sustained episode.",
        "LOC_008",
        "A",
        None,
        ["PRS_000", "PRS_003"],
        ["sex_magick", "visionary_work", "relationship", "magick"],
        [],
    ),
    ev(
        "EVT_033",
        "1919",
        "1919",
        "The Blue Equinox",
        "Crowley consolidates postwar doctrine in The Blue Equinox, a publication that bridges the New York exile and the communal ambitions that follow in Sicily.",
        "LOC_008",
        "A",
        "DOC_WKS_009",
        ["PRS_000"],
        ["publication", "magazine", "doctrine", "postwar"],
        ["WKS_009"],
    ),
    ev(
        "EVT_034",
        "1920",
        "1920",
        "The Abbey of Thelema is established",
        "Crowley establishes the Abbey of Thelema at Cefalu, turning Sicily into his most visible laboratory for communal discipline, ritual experiment, and social control.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003"],
        ["abbey_of_thelema", "community", "travel", "magick", "sex_magick"],
        [],
    ),
    ev(
        "EVT_035",
        "1920",
        "1921",
        "Leah Hirsig as Scarlet Woman",
        "Leah Hirsig becomes the Abbey's most conspicuous Scarlet Woman figure, carrying the symbolic role while also helping keep the place running day to day.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003"],
        ["relationship", "scarlet_woman", "sex_magick", "abbey_of_thelema"],
        [],
    ),
    ev(
        "EVT_036",
        "1920",
        "1922",
        "Jane Wolfe at the Abbey",
        "Jane Wolfe joins the Abbey milieu and leaves one of the clearest witness records for Crowley's routines, discipline, and practical training methods.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003", "PRS_008"],
        ["disciples", "abbey_of_thelema", "initiation", "testimony"],
        [],
    ),
    ev(
        "EVT_037",
        "1921",
        "1922",
        "Ritual discipline, sex, and drugs at the Abbey",
        "The Abbey years intensify ritual austerity, sexual magic, opium and cocaine use, and the heavily supervised communal life that later accounts turn into notoriety.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003", "PRS_008"],
        ["sex", "drugs", "discipline", "abbey_of_thelema", "magick"],
        [],
    ),
    ev(
        "EVT_038",
        "1922",
        "1922",
        "Diary of a Drug Fiend",
        "Crowley publishes Diary of a Drug Fiend, fictionalizing addiction, discipline, and transformation in a novel that remains one of his most recognizable books.",
        "LOC_007",
        "B",
        "DOC_WKS_012",
        ["PRS_000"],
        ["publication", "drugs", "fiction", "discipline"],
        ["WKS_012"],
    ),
    ev(
        "EVT_039",
        "1922",
        "1923",
        "Raoul Loveday and the Abbey scandal",
        "Raoul Loveday's death and the surrounding rumors turn the Abbey into a press spectacle and give later biographers a stark example of the gap between ritual practice and sensational reporting.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003", "PRS_008"],
        ["scandal", "drugs", "death", "abbey_of_thelema", "press"],
        [],
    ),
    ev(
        "EVT_040",
        "1923",
        "1923",
        "Expulsion from Italy",
        "The Italian authorities expel Crowley and the Abbey closes, ending his most famous communal experiment and scattering its participants across Europe.",
        "LOC_007",
        "E",
        None,
        ["PRS_000", "PRS_003"],
        ["legal_trouble", "expulsion", "abbey_of_thelema", "politics"],
        [],
    ),
    ev(
        "EVT_041",
        "1923",
        "1924",
        "Eccentrics in exile: Tunis and Paris",
        "Crowley moves through North African and French exile, trying to keep writing, correspondence, and reputation alive while his finances and health become less stable.",
        "LOC_016",
        "E",
        None,
        ["PRS_000"],
        ["exile", "travel", "finance", "writing"],
        [],
    ),
    ev(
        "EVT_042",
        "1924",
        "1925",
        "The French connection and Hanni Jaeger",
        "Crowley's continental social life shifts into the orbit of Hanni Jaeger and the Berlin-Paris fringe, where sex, art, travel, and publicity continue to overlap.",
        "LOC_006",
        "E",
        None,
        ["PRS_000"],
        ["relationship", "sex", "travel", "art", "exile"],
        [],
    ),
    ev(
        "EVT_043",
        "1925",
        "1928",
        "Cocaine, heroin, and financial decline",
        "The middle 1920s bring a harsher cycle of drug dependency, debt, and difficult living arrangements, even as Crowley keeps producing letters, ritual material, and journalism.",
        "LOC_006",
        "E",
        None,
        ["PRS_000"],
        ["drugs", "finance", "correspondence", "decline"],
        [],
    ),
    ev(
        "EVT_044",
        "1929",
        "1929",
        "Magick in Theory and Practice",
        "Crowley publishes one of his clearest manuals of method, presenting magical theory in a form that later readers continue to mine for practical concepts.",
        "LOC_006",
        "A",
        "DOC_WKS_010",
        ["PRS_000"],
        ["publication", "magick", "manual", "theory"],
        ["WKS_010"],
    ),
    ev(
        "EVT_045",
        "1929",
        "1929",
        "The Confessions of Aleister Crowley",
        "Crowley's autobiography appears as an expansive self-interpreting life story and remains a crucial but unreliable source for the archive.",
        "LOC_006",
        "B",
        "DOC_WKS_011",
        ["PRS_000"],
        ["publication", "autobiography", "self_report", "literary_formation"],
        ["WKS_011"],
    ),
    ev(
        "EVT_046",
        "1930",
        "1932",
        "Berlin and Weimar-era art circles",
        "Crowley moves through Berlin's art and cabaret worlds, where painting, performance, and sexual politics give him a late-life public setting different from the Abbey or the ritual scene.",
        "LOC_017",
        "E",
        None,
        ["PRS_000"],
        ["art", "travel", "performance", "sexuality"],
        [],
    ),
    ev(
        "EVT_047",
        "1931",
        "1932",
        "Crowley's Berlin exhibition and public persona",
        "Crowley's artwork receives a Berlin exhibition and his Weimar public image is reframed as that of a cosmopolitan outsider artist and occult celebrity.",
        "LOC_017",
        "E",
        None,
        ["PRS_000"],
        ["art", "reception", "public_image", "berlin"],
        [],
    ),
    ev(
        "EVT_048",
        "1934",
        "1935",
        "The Black Magic libel case",
        "Crowley keeps fighting the press and the courts as libel, obscenity, and anti-occult headlines continue to define his public image.",
        "LOC_003",
        "E",
        None,
        ["PRS_000"],
        ["legal_trouble", "press", "libel", "public_image"],
        [],
    ),
    ev(
        "EVT_049",
        "1935",
        "1936",
        "Hastings becomes the final base",
        "Crowley settles into Hastings, which becomes his last long-term home and the main station for his final letters, manuscripts, and declining health.",
        "LOC_009",
        "E",
        None,
        ["PRS_000"],
        ["travel", "home", "decline", "correspondence"],
        [],
    ),
    ev(
        "EVT_050",
        "1937",
        "1943",
        "Correspondence with Regardie and disciples",
        "Crowley continues to write to Israel Regardie and other disciples, helping preserve ritual material, interpretive comments, and the practical transmission of his work.",
        "LOC_009",
        "E",
        None,
        ["PRS_000", "PRS_011"],
        ["correspondence", "disciples", "transmission", "reception"],
        [],
    ),
    ev(
        "EVT_051",
        "1939",
        "1943",
        "Wartime isolation and manuscript work",
        "The war years leave Crowley more isolated, but he keeps producing notes, letters, and revisions that sustain the archive through the late period.",
        "LOC_009",
        "E",
        None,
        ["PRS_000"],
        ["war", "manuscripts", "correspondence", "decline"],
        [],
    ),
    ev(
        "EVT_052",
        "1944",
        "1944",
        "The Book of Thoth",
        "Crowley publishes The Book of Thoth, his tarot manual and one of the clearest late statements of his symbolic revisions to the Tree of Life and tarot correspondences.",
        "LOC_003",
        "B",
        "DOC_WKS_005",
        ["PRS_000"],
        ["publication", "tarot", "qabalah", "magick"],
        ["WKS_005"],
    ),
    ev(
        "EVT_053",
        "1945",
        "1946",
        "Jack Parsons and the Agape Lodge",
        "Crowley receives correspondence from Jack Parsons and the California occult milieu, giving the late story an American successor thread tied to rocket culture and postwar Thelema.",
        "LOC_020",
        "E",
        None,
        ["PRS_000", "PRS_009"],
        ["correspondence", "disciples", "oto", "postwar_reception"],
        [],
    ),
    ev(
        "EVT_054",
        "1945",
        "1947",
        "Kenneth Grant and succession concerns",
        "Kenneth Grant enters the orbit of Crowley's late network, reflecting the succession and interpretation problems that begin before Crowley's death and intensify afterward.",
        "LOC_009",
        "E",
        None,
        ["PRS_000", "PRS_010"],
        ["correspondence", "disciples", "succession", "reception"],
        [],
    ),
    ev(
        "EVT_055",
        "1946",
        "1947",
        "Final illness and decline",
        "Crowley's health worsens in Hastings while he continues to write, receive visitors, and keep a precarious control over the archive of his own life.",
        "LOC_009",
        "E",
        None,
        ["PRS_000"],
        ["illness", "decline", "correspondence", "home"],
        [],
    ),
    ev(
        "EVT_056",
        "1947-12-01",
        None,
        "Death of Aleister Crowley",
        "Crowley dies in Hastings, ending the biographical arc that the portal tracks through the documentary and magical record.",
        "LOC_009",
        "E",
        None,
        ["PRS_000"],
        ["death", "legacy", "biography"],
        [],
    ),
    ev(
        "EVT_057",
        "1947-12",
        "1948",
        "Funeral, cremation, and immediate aftermath",
        "The funeral and cremation create the first posthumous circulation of Crowley's remains, memorabilia, and reputation, setting up the long afterlife of the archive.",
        "LOC_009",
        "E",
        None,
        ["PRS_000"],
        ["death", "legacy", "archive", "reception"],
        [],
    ),
    ev(
        "EVT_058",
        "1948",
        "1950",
        "Preservation by disciples and editors",
        "Regardie and other disciples help preserve, edit, and transmit Crowley's material after his death, making the posthumous archive much easier to browse and reuse.",
        "LOC_003",
        "E",
        None,
        ["PRS_011", "PRS_016"],
        ["reception", "archive", "editing", "transmission"],
        [],
    ),
    ev(
        "EVT_059",
        "1952",
        "1952",
        "Jack Parsons and the rocket-age afterlife",
        "Parsons' death and the continuing myth of Crowley in American occult culture show how quickly the magician's name became part of a larger postwar symbolic economy.",
        "LOC_020",
        "E",
        None,
        ["PRS_009"],
        ["reception", "postwar", "disciples", "occult_culture"],
        [],
    ),
    ev(
        "EVT_060",
        "2002",
        "2002",
        "Kaczynski publishes Perdurabo",
        "Richard Kaczynski's biography arrives as a major scholarly reset for Crowley studies and becomes one of the archive's core biographical source texts.",
        "LOC_003",
        "C",
        None,
        ["PRS_013"],
        ["scholarship", "biography", "reception", "crowley_studies"],
        [],
    ),
    ev(
        "EVT_061",
        "2012",
        "2012",
        "Revised and expanded Perdurabo",
        "The revised and expanded edition of Perdurabo widens the documentary base around Crowley's life and makes the modern scholarly consensus easier to browse in one place.",
        "LOC_003",
        "C",
        None,
        ["PRS_013", "PRS_016"],
        ["scholarship", "biography", "reception", "crowley_studies"],
        [],
    ),
    ev(
        "EVT_062",
        "2014",
        "2014",
        "Churton's Berlin-focused reassessment",
        "Tobias Churton's Berlin biography reframes Crowley through art, sex, and Weimar culture, adding a sharper reception lane for the later-period archive.",
        "LOC_017",
        "C",
        None,
        ["PRS_014"],
        ["scholarship", "biography", "reception", "art", "weimar"],
        [],
    ),
    ev(
        "EVT_063",
        "2013",
        "2013",
        "Churton's India-focused reassessment",
        "Churton's India study strengthens the travel and Eastern mysticism line in Crowley scholarship and provides a useful counterpoint to the autobiographical record.",
        "LOC_015",
        "C",
        None,
        ["PRS_014"],
        ["scholarship", "biography", "reception", "india", "travel"],
        [],
    ),
    ev(
        "EVT_064",
        "2010",
        "2020",
        "Academic and pop-culture reassessment",
        "Crowley continues to be reinterpreted through scholarship, music culture, occult revival, and digital archives, keeping the posthumous reception layer active.",
        "LOC_003",
        "C",
        None,
        ["PRS_013", "PRS_014", "PRS_015", "PRS_016"],
        ["scholarship", "reception", "pop_culture", "archive"],
        [],
    ),
]


PERSON_EVENTS = []
for event in EVENTS:
    for person_id in event["people"]:
        PERSON_EVENTS.append((person_id, event["id"]))


def seed_timeline_map():
    conn = open_db()
    cursor = conn.cursor()

    topic_taxonomy = json.loads(TOPIC_TAXONOMY_PATH.read_text(encoding="utf-8"))
    topic_id_by_slug = {item["slug"]: item["id"] for item in topic_taxonomy["topics"]}

    cursor.execute("DELETE FROM locations")
    cursor.executemany(
        """
        INSERT INTO locations (id, name, latitude, longitude, significance)
        VALUES (?, ?, ?, ?, ?)
        """,
        LOCATIONS,
    )

    cursor.execute("DELETE FROM event_topics")
    cursor.execute("DELETE FROM topics")
    cursor.executemany(
        """
        INSERT INTO topics (id, slug, label, description, sort_order)
        VALUES (?, ?, ?, ?, ?)
        """,
        [
            (
                item["id"],
                item["slug"],
                item["label"],
                item.get("description"),
                item.get("sort_order", 0),
            )
            for item in topic_taxonomy["topics"]
        ],
    )

    cursor.execute("DELETE FROM person_events")
    cursor.execute("DELETE FROM events")

    cursor.executemany(
        """
        INSERT INTO events (id, date_start, date_end, title, description, location_id, evidentiary_lane, document_id)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        [
            (
                event["id"],
                event["date_start"],
                event["date_end"],
                event["title"],
                build_description(event["summary"], event["topics"], event["people"], event["works"]),
                event["location_id"],
                event["lane"],
                event["document_id"],
            )
            for event in EVENTS
        ],
    )

    cursor.executemany(
        """
        INSERT OR IGNORE INTO person_events (person_id, event_id)
        VALUES (?, ?)
        """,
        PERSON_EVENTS,
    )

    cursor.executemany(
        """
        INSERT INTO event_topics (event_id, topic_id)
        VALUES (?, ?)
        """,
        [
            (event["id"], topic_id_by_slug[topic])
            for event in EVENTS
            for topic in event["topics"]
            if topic in topic_id_by_slug
        ],
    )

    conn.commit()
    conn.close()
    print(
        f"Seeded {len(LOCATIONS)} locations, {len(EVENTS)} events, {len(PERSON_EVENTS)} person-event links, "
        f"and {len(topic_taxonomy['topics'])} topics."
    )


if __name__ == "__main__":
    seed_timeline_map()
